services:
  - type: web
    name: universal-document-converter
    env: node
    buildCommand: |
      npm install
      apt-get update && apt-get install -y wkhtmltopdf
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 